export interface WpCategory {
  id: number;
  name: string;
}

export const WP_CATEGORIES: WpCategory[] = [
  { id: 266, name: 'Adventure Sports' },
  { id: 303, name: 'Beach Webcams' },
  { id: 262, name: 'Beaches & Islands' },
  { id: 1,   name: 'Blog & News' },
  { id: 231, name: 'Brač' },
  { id: 258, name: 'Budget & Costs' },
  { id: 246, name: 'Central Croatia' },
  { id: 280, name: 'Connectivity' },
  { id: 269, name: 'Croatian Cuisine' },
  { id: 224, name: 'Dalmatia' },
  { id: 288, name: 'Dalmatian Coast Webcams' },
  { id: 223, name: 'Destinations' },
  { id: 226, name: 'Dubrovnik' },
  { id: 290, name: 'Dubrovnik Webcams' },
  { id: 275, name: 'First-Time Visitors' },
  { id: 268, name: 'Food & Drink' },
  { id: 272, name: 'Food Tours' },
  { id: 257, name: 'Getting Around' },
  { id: 283, name: 'Hidden Gems' },
  { id: 264, name: 'Hiking & Nature' },
  { id: 265, name: 'History & Culture' },
  { id: 229, name: 'Hvar' },
  { id: 291, name: 'Hvar Webcams' },
  { id: 238, name: 'Inland Istria' },
  { id: 281, name: 'Inspiration' },
  { id: 302, name: 'Island Webcams' },
  { id: 233, name: 'Istria' },
  { id: 294, name: 'Istrian Webcams' },
  { id: 255, name: 'Itineraries' },
  { id: 251, name: 'Kornati' },
  { id: 230, name: 'Korčula' },
  { id: 292, name: 'Korčula Webcams' },
  { id: 242, name: 'Krk Island' },
  { id: 250, name: 'Krka' },
  { id: 239, name: 'Kvarner' },
  { id: 299, name: 'Kvarner Webcams' },
  { id: 276, name: 'Language & Etiquette' },
  { id: 287, name: 'Live Webcams' },
  { id: 284, name: 'Local Stories' },
  { id: 305, name: 'Marina & Harbor Webcams' },
  { id: 273, name: 'Markets' },
  { id: 252, name: 'Mljet' },
  { id: 279, name: 'Money & Payments' },
  { id: 237, name: 'Motovun' },
  { id: 304, name: 'National Park Webcams' },
  { id: 248, name: 'National Parks' },
  { id: 241, name: 'Opatija' },
  { id: 300, name: 'Opatija Webcams' },
  { id: 232, name: 'Other Dalmatian Islands' },
  { id: 253, name: 'Other Parks' },
  { id: 278, name: 'Packing Lists' },
  { id: 282, name: 'Photo Essays' },
  { id: 249, name: 'Plitvice Lakes' },
  { id: 236, name: 'Poreč' },
  { id: 297, name: 'Poreč Webcams' },
  { id: 235, name: 'Pula' },
  { id: 296, name: 'Pula Webcams' },
  { id: 243, name: 'Rab Island' },
  { id: 271, name: 'Restaurants' },
  { id: 240, name: 'Rijeka' },
  { id: 301, name: 'Rijeka Webcams' },
  { id: 234, name: 'Rovinj' },
  { id: 295, name: 'Rovinj Webcams' },
  { id: 277, name: 'Safety & Health' },
  { id: 263, name: 'Sailing & Boating' },
  { id: 285, name: 'Seasonal Highlights' },
  { id: 247, name: 'Slavonia & Eastern Croatia' },
  { id: 286, name: 'Special Interests' },
  { id: 225, name: 'Split' },
  { id: 289, name: 'Split Webcams' },
  { id: 261, name: 'Things to Do' },
  { id: 274, name: 'Travel Tips' },
  { id: 254, name: 'Trip Planning' },
  { id: 259, name: 'Visas & Entry' },
  { id: 267, name: 'Wellness & Relaxation' },
  { id: 256, name: 'When to Visit' },
  { id: 260, name: 'Where to Stay' },
  { id: 270, name: 'Wine Regions' },
  { id: 227, name: 'Zadar' },
  { id: 293, name: 'Zadar Webcams' },
  { id: 245, name: 'Zagreb' },
  { id: 244, name: 'Zagreb & Central Croatia' },
  { id: 298, name: 'Zagreb Webcams' },
  { id: 228, name: 'Šibenik' },
];
